
zgw-office-addin:
  enabled: false
  fullnameOverride: "zgw-office-addin"
  frontend:
    # ghcr.io/infonl/zgw-office-add-in-frontend:v0.0.205
    image:
      tag: v0.0.299
    # the public url where manifest.xml and static js files are served
    frontendUrl: http://office-addin.example.com
    # by default this is not needed as it is proxied by the frontend host
    backendPublicUrl: ""
    # can be enabled if needed, if for instance you don't want an ingress
    enableHttps: false
  backend:
    # ghcr.io/infonl/zgw-office-add-in-backend:
    image:
      tag: v0.0.299
    # secret used to generate and validate JWT tokens
    jwtSecret: "YOUR_SECRET_KEY"
    # the base url of the openzaak api's
    apiBaseUrl: "http://openzaak.example.com"


pabc:
  enabled: false
  fullnameOverride: "pabc"
  postgresql:
    enabled: false
  image:
    # this is the same version as the chart by default, so consider leaving this empty
    tag: v0.0.1-rc.5
  migrations:
    image:
      # this is the same version as the chart by default, so consider leaving this empty
      tag: v0.0.1-rc.5
  
  settings:
    database:
      host: ""
      port: 5432
      name: "pabc"
      username: "pabc"
      password: "SECRET__SECRET__SECRET"

    apiKeys: ["SECRET__SECRET__SECRET"]
    
    oidc:
      authority: "https://ontw-keycloak-admin.dimpact.icatt.nl/realms/podiumd"
      clientId: "pabc"
      clientSecret: "SECRET__SECRET__SECRET"
      functioneelBeheerderRole: "administrator"
      nameClaimType: "preferred_username"
      roleClaimType: "roles"
      emailClaimType: "email"

    # this will be use in the next version
    # keycloakAdmin:
    #   clientId: "pabc-keycloak-admin"
    #   clientSecret: "SECRET__SECRET__SECRET"
  
